"""Scalp shadow v1 — comparison report.

Reads ml_setups rows generated by the scalp shadow experiment and produces a
fees-adjusted, baseline-relative summary so we can decide whether any signal
has edge worth promoting to live.

Plan: docs/plans/scalp_shadow_v1.md.

Filter contract:
    experiment_id = settings.SCALP_EXPERIMENT_ID
    setup_type    IN settings.SCALP_SETUP_TYPES
    outcome_type  IS NOT NULL
    outcome_type  NOT IN data_service.data_store.NON_MARKET_OUTCOMES

Per-signal metrics:
    N                       resolved sample size
    wins / losses / flat    raw split (wins = pnl_pct > 0 after fees)
    WR_raw / WR_post_fees   fraction with positive pnl_pct (with/without fees)
    PF_raw / PF_post_fees   sum(positive pnl_pct) / sum(|negative pnl_pct|)
    avg_pnl_pct             mean pnl_pct (post-fees, percent units)
    avg_trade_duration_min  mean trade_duration_ms / 60_000
    freq_per_day            N / window_days

Decision rule (run for every signal except the random baseline):
    PASS iff all of:
        N >= 100
        WR_post_fees > 0.50
        PF_post_fees > 1.5
        WR_post_fees - WR_baseline_post_fees >= 0.15
        freq_per_day >= 5.0
    Otherwise FAIL.

Usage:
    python scripts/report_scalp_shadow.py
    python scripts/report_scalp_shadow.py --since 2026-05-01
    python scripts/report_scalp_shadow.py --pair BTC/USDT
"""
from __future__ import annotations

import argparse
import math
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import psycopg2
from psycopg2.extras import RealDictCursor

from config.settings import settings
from data_service.data_store import (
    NON_MARKET_OUTCOMES,
    ml_market_outcome_filter_sql,
)


_BASELINE_TYPE = "scalp_random_baseline_v1"


@dataclass
class SignalStats:
    setup_type: str
    n: int
    wins: int
    losses: int
    flat: int
    wr_raw: float
    wr_post_fees: float
    pf_raw: float
    pf_post_fees: float
    avg_pnl_pct: float          # post-fees, percent units
    avg_trade_duration_min: float
    freq_per_day: float
    window_days: float

    def as_table_row(self, baseline_wr: float | None) -> list[str]:
        wr_diff = ""
        if baseline_wr is not None and self.setup_type != _BASELINE_TYPE:
            wr_diff = f"{(self.wr_post_fees - baseline_wr) * 100:+.1f}pp"
        return [
            self.setup_type,
            str(self.n),
            f"{self.wins}/{self.losses}/{self.flat}",
            f"{self.wr_raw * 100:.1f}%",
            f"{self.wr_post_fees * 100:.1f}%",
            wr_diff,
            f"{self.pf_raw:.2f}" if math.isfinite(self.pf_raw) else "inf",
            f"{self.pf_post_fees:.2f}" if math.isfinite(self.pf_post_fees) else "inf",
            f"{self.avg_pnl_pct:+.3f}%",
            f"{self.avg_trade_duration_min:.1f}",
            f"{self.freq_per_day:.2f}",
        ]


def _conn():
    return psycopg2.connect(
        host=settings.POSTGRES_HOST, port=settings.POSTGRES_PORT,
        dbname=settings.POSTGRES_DB, user=settings.POSTGRES_USER,
        password=settings.POSTGRES_PASSWORD,
    )


def _fetch_rows(*, since: str | None, pair: str | None) -> list[dict]:
    setup_types = settings.SCALP_SETUP_TYPES
    if not setup_types:
        return []

    sql = f"""
        SELECT setup_type, pair, direction, outcome_type,
               pnl_pct, pnl_usd, trade_duration_ms, fill_duration_ms,
               created_at, resolved_at
        FROM ml_setups
        WHERE experiment_id = %s
          AND setup_type = ANY(%s)
          AND outcome_type IS NOT NULL
          AND {ml_market_outcome_filter_sql()}
    """
    params: list = [settings.SCALP_EXPERIMENT_ID, list(setup_types)]
    if since:
        sql += " AND created_at >= %s"
        params.append(since)
    if pair:
        sql += " AND pair = %s"
        params.append(pair)
    sql += " ORDER BY created_at ASC"

    with _conn() as c, c.cursor(cursor_factory=RealDictCursor) as cur:
        cur.execute(sql, params)
        return [dict(r) for r in cur.fetchall()]


def _compute_stats(setup_type: str, rows: list[dict],
                   fee_fraction: float) -> SignalStats | None:
    if not rows:
        return None
    pnls_post: list[float] = []
    durations_min: list[float] = []
    for r in rows:
        if r.get("pnl_pct") is None:
            continue
        # pnl_pct is stored as a fraction; fee_fraction is also a fraction.
        adjusted = float(r["pnl_pct"]) - fee_fraction
        pnls_post.append(adjusted)
        if r.get("trade_duration_ms"):
            durations_min.append(float(r["trade_duration_ms"]) / 60_000.0)

    n = len(pnls_post)
    if n == 0:
        return None

    raw_pnls = [float(r["pnl_pct"]) for r in rows if r.get("pnl_pct") is not None]
    wr_raw = sum(1 for p in raw_pnls if p > 0) / max(1, len(raw_pnls))
    wins_post = sum(1 for p in pnls_post if p > 0)
    losses_post = sum(1 for p in pnls_post if p < 0)
    flat_post = n - wins_post - losses_post
    wr_post = wins_post / n

    gross_win_raw = sum(p for p in raw_pnls if p > 0)
    gross_loss_raw = sum(-p for p in raw_pnls if p < 0)
    pf_raw = (gross_win_raw / gross_loss_raw) if gross_loss_raw > 0 else math.inf

    gross_win_post = sum(p for p in pnls_post if p > 0)
    gross_loss_post = sum(-p for p in pnls_post if p < 0)
    pf_post = (gross_win_post / gross_loss_post) if gross_loss_post > 0 else math.inf

    avg_pnl_pct = (sum(pnls_post) / n) * 100  # display as percent

    timestamps = [r["created_at"] for r in rows if r.get("created_at")]
    if len(timestamps) >= 2:
        span_days = max(
            (max(timestamps) - min(timestamps)).total_seconds() / 86400.0,
            1.0 / 24,  # at least 1 hour to avoid divide-by-near-zero
        )
    else:
        span_days = 1.0
    freq_per_day = n / span_days

    avg_trade_min = sum(durations_min) / len(durations_min) if durations_min else 0.0

    return SignalStats(
        setup_type=setup_type, n=n,
        wins=wins_post, losses=losses_post, flat=flat_post,
        wr_raw=wr_raw, wr_post_fees=wr_post,
        pf_raw=pf_raw, pf_post_fees=pf_post,
        avg_pnl_pct=avg_pnl_pct,
        avg_trade_duration_min=avg_trade_min,
        freq_per_day=freq_per_day,
        window_days=span_days,
    )


def _decision(stats: SignalStats, baseline_wr: float | None) -> tuple[bool, list[str]]:
    """Return (passes, list of failed-rule strings)."""
    failures: list[str] = []
    if stats.n < 100:
        failures.append(f"N={stats.n} < 100")
    if stats.wr_post_fees <= 0.50:
        failures.append(f"WR_post_fees={stats.wr_post_fees * 100:.1f}% <= 50%")
    if not (math.isinf(stats.pf_post_fees) or stats.pf_post_fees > 1.5):
        failures.append(f"PF_post_fees={stats.pf_post_fees:.2f} <= 1.5")
    if baseline_wr is not None:
        delta = stats.wr_post_fees - baseline_wr
        if delta < 0.15:
            failures.append(
                f"WR_post_fees - baseline = {delta * 100:+.1f}pp < +15pp"
            )
    if stats.freq_per_day < 5.0:
        failures.append(f"freq_per_day={stats.freq_per_day:.2f} < 5/day")
    return (len(failures) == 0), failures


def _print_markdown(stats_by_type: dict[str, SignalStats],
                    baseline_wr: float | None,
                    args) -> None:
    print(f"# Scalp Shadow Report — {settings.SCALP_EXPERIMENT_ID}")
    print()
    filt = []
    if args.since:
        filt.append(f"since={args.since}")
    if args.pair:
        filt.append(f"pair={args.pair}")
    if filt:
        print(f"_Filter: {' '.join(filt)}_")
        print()
    print(f"_Round-trip fee subtracted: {settings.SCALP_ROUND_TRIP_FEE_PCT}% per trade._")
    print()

    headers = [
        "setup_type", "N", "W/L/F", "WR_raw", "WR_post", "Δ vs baseline",
        "PF_raw", "PF_post", "avg_pnl", "avg_dur(min)", "freq/day",
    ]
    sep = ["---"] * len(headers)
    rows: list[list[str]] = []
    # Baseline first for orientation, then signals in registry order.
    ordered = [_BASELINE_TYPE] + [
        t for t in settings.SCALP_SETUP_TYPES if t != _BASELINE_TYPE
    ]
    for t in ordered:
        s = stats_by_type.get(t)
        if s is None:
            rows.append([t, "0"] + [""] * (len(headers) - 2))
            continue
        rows.append(s.as_table_row(baseline_wr))

    print("| " + " | ".join(headers) + " |")
    print("| " + " | ".join(sep) + " |")
    for r in rows:
        print("| " + " | ".join(r) + " |")
    print()

    print("## Decision rule per signal")
    print()
    for t in settings.SCALP_SETUP_TYPES:
        if t == _BASELINE_TYPE:
            continue
        s = stats_by_type.get(t)
        if s is None:
            print(f"- **{t}**: SKIP — no resolved samples.")
            continue
        passed, fails = _decision(s, baseline_wr)
        if passed:
            print(f"- **{t}**: PASS — N={s.n}, WR_post={s.wr_post_fees * 100:.1f}%, "
                  f"PF_post={s.pf_post_fees:.2f}, freq={s.freq_per_day:.2f}/day.")
        else:
            print(f"- **{t}**: FAIL — " + "; ".join(fails))
    if baseline_wr is None:
        print()
        print("> Baseline WR not available — comparative rule (Δ >= +15pp) "
              "skipped. Decisions above ignore that criterion.")
    print()
    print("## Outcome breakdown")
    print()
    print("Outcomes excluded from the metrics above: " +
          ", ".join(sorted(NON_MARKET_OUTCOMES)) + ".")


def main() -> int:
    parser = argparse.ArgumentParser(description="Scalp shadow comparison report")
    parser.add_argument("--since", default=None,
                        help="ISO timestamp filter on created_at (e.g. 2026-05-01)")
    parser.add_argument("--pair", default=None, help="Limit to a single pair")
    args = parser.parse_args()

    rows = _fetch_rows(since=args.since, pair=args.pair)
    if not rows:
        print(f"No resolved scalp samples found for "
              f"experiment_id={settings.SCALP_EXPERIMENT_ID}.")
        return 0

    by_type: dict[str, list[dict]] = {}
    for r in rows:
        by_type.setdefault(r["setup_type"], []).append(r)

    fee_fraction = float(settings.SCALP_ROUND_TRIP_FEE_PCT) / 100.0
    stats_by_type: dict[str, SignalStats] = {}
    for t, rs in by_type.items():
        s = _compute_stats(t, rs, fee_fraction)
        if s is not None:
            stats_by_type[t] = s

    baseline_wr = None
    if _BASELINE_TYPE in stats_by_type:
        baseline_wr = stats_by_type[_BASELINE_TYPE].wr_post_fees

    _print_markdown(stats_by_type, baseline_wr, args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
